# Задание 5: Использование словаря
note0 = ("Имя пользователя: ","Содержание заметки: ","Статус заметки: ","Дата создания заметки в формате {10-11-2024}: ", "Дата истечения заметки (дедлайн) в формате {10-11-2024}: ","Заголовок: ")
note = ("username", "content", "status", "created_date", "issue_date", "titles")
note_dict = dict.fromkeys(note, "Ввод текста")
note_dict ["titles"] = [1,2,3]
print(note0)
print(note)
print(note_dict)
note_dict ["username"] = input(note0[0])
note_dict ["content"] = input(note0[1])
note_dict ["status"] = input(note0[2])
note_dict ["created_date"] = input(note0[3])
note_dict ["issue_date"] = input(note0[4])
note_dict ["titles"][0] = input(note0[5]+"1: ")
note_dict ["titles"][1] = input(note0[5]+"2: ")
note_dict ["titles"][2] = input(note0[5]+"3: ")
print(note_dict)
# temp_created_date = note[3][0: 5]
# temp_issue_date = note[4][0: 5]
# print(note0[0],note_dict ["username"])
# print(note)
# print(note0[0], note[0])
# print(note0[1], note[1])
# print(note0[2], note[2])
# print(note0[3][:21]+": ", temp_created_date)
# print(note0[4][:22]+": ", temp_issue_date)
# print(note0[5][0], note[5][0])
# print(note0[5][1], note[5][1])
# print(note0[5][2], note[5][2])